name: CI

# Aqui dizemos que o workflow deve ser executado quando houver um push na branch 'main'
on:
  push:
    branches:
      - main

# Definimos o trabalho a ser feito
jobs:
  test:
    runs-on: ubuntu-latest  # O trabalho será executado em uma máquina Linux

    steps:
      - name: Checar o código
        uses: actions/checkout@v2  # Faz o checkout do código no repositório

      - name: Configurar Node.js
        uses: actions/setup-node@v2  # Configura o Node.js no ambiente
        with:
          node-version: '14'  # Especifica a versão do Node.js

      - name: Instalar dependências
        run: npm install  # Instala as dependências do projeto

      - name: Executar testes
        run: npm test  # Executa os testes
